version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: mymongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./countries.json:/countries.json:ro
    command: >
      bash -c "
        mongod --bind_ip_all & 
        sleep 10 && 
        mongoimport --db countries_db --collection countries --file /countries.json --jsonArray --drop
        wait
      "

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DB=countries_db
      - MONGODB_COLLECTION=countries
    depends_on:
      - mongo

  test:
    build: .
    container_name: fastapi-test
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DB=countries_db
      - MONGODB_COLLECTION=countries 
      - PYTHONPATH=/backend
    depends_on:
      - mongo
    command: >
      sh -c "sleep 15 && pytest tests"